package backtest

import (
	"math"
	"strings"

	"github.com/yui666a/rakuten-api-leverage-exchange/backend/internal/domain/entity"
)

// SignalSource* are the canonical keys used in BySignalSource maps. The
// string literals match the StrategyEngine's Reason prefix in
// internal/usecase/strategy.go. If that file's reason phrasing changes,
// parseSignalSource must be updated in lockstep (guarded by tests).
const (
	SignalSourceTrendFollow = "trend_follow"
	SignalSourceContrarian  = "contrarian"
	SignalSourceBreakout    = "breakout"
	SignalSourceUnknown     = "unknown"
)

// parseSignalSource classifies a trade by inspecting the engine-produced
// ReasonEntry string. The prefixes ("trend follow:", "contrarian:",
// "breakout:") are generated by StrategyEngine in a small number of
// call sites; any unrecognised prefix maps to SignalSourceUnknown so the
// breakdown is total (sum of bucket counts == total trades).
func parseSignalSource(reasonEntry string) string {
	lower := strings.ToLower(strings.TrimSpace(reasonEntry))
	switch {
	case strings.HasPrefix(lower, "trend follow"):
		return SignalSourceTrendFollow
	case strings.HasPrefix(lower, "contrarian"):
		return SignalSourceContrarian
	case strings.HasPrefix(lower, "breakout"):
		return SignalSourceBreakout
	default:
		return SignalSourceUnknown
	}
}

// computeBreakdown aggregates a pre-filtered slice of trades into a single
// SummaryBreakdown. Conventions match SummaryReporter.BuildSummary:
//   - PnL >= 0 counts as a win (zero pnl is rare and conventionally a win).
//   - ProfitFactor is 0 when either side (wins or losses) is zero, avoiding
//     division-by-zero and matching reporter.go's behaviour.
func computeBreakdown(trades []entity.BacktestTradeRecord) entity.SummaryBreakdown {
	out := entity.SummaryBreakdown{Trades: len(trades)}
	if out.Trades == 0 {
		return out
	}
	sumWins := 0.0
	sumLosses := 0.0 // positive magnitude
	total := 0.0
	for _, t := range trades {
		total += t.PnL
		if t.PnL >= 0 {
			out.WinTrades++
			sumWins += t.PnL
		} else {
			out.LossTrades++
			sumLosses += math.Abs(t.PnL)
		}
	}
	out.WinRate = float64(out.WinTrades) / float64(out.Trades) * 100
	out.TotalPnL = total
	out.AvgPnL = total / float64(out.Trades)
	if sumLosses > 0 && sumWins > 0 {
		out.ProfitFactor = sumWins / sumLosses
	}
	return out
}

// BuildBreakdown buckets trades by keyFunc and produces a breakdown per
// bucket. Empty input returns an empty, non-nil map so callers can unmarshal
// it with ",omitempty" JSON tags without surprises.
func BuildBreakdown(
	trades []entity.BacktestTradeRecord,
	keyFunc func(entity.BacktestTradeRecord) string,
) map[string]entity.SummaryBreakdown {
	if len(trades) == 0 {
		return map[string]entity.SummaryBreakdown{}
	}
	buckets := make(map[string][]entity.BacktestTradeRecord, 4)
	for _, t := range trades {
		key := keyFunc(t)
		buckets[key] = append(buckets[key], t)
	}
	out := make(map[string]entity.SummaryBreakdown, len(buckets))
	for key, ts := range buckets {
		out[key] = computeBreakdown(ts)
	}
	return out
}
