/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkForwardRouteImport } from './routes/walk-forward'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BacktestMultiRouteImport } from './routes/backtest-multi'
import { Route as BacktestDecisionsRouteImport } from './routes/backtest-decisions'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const WalkForwardRoute = WalkForwardRouteImport.update({
  id: '/walk-forward',
  path: '/walk-forward',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestMultiRoute = BacktestMultiRouteImport.update({
  id: '/backtest-multi',
  path: '/backtest-multi',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestDecisionsRoute = BacktestDecisionsRouteImport.update({
  id: '/backtest-decisions',
  path: '/backtest-decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/backtest-decisions': typeof BacktestDecisionsRoute
  '/backtest-multi': typeof BacktestMultiRoute
  '/history': typeof HistoryRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/walk-forward': typeof WalkForwardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/backtest-decisions': typeof BacktestDecisionsRoute
  '/backtest-multi': typeof BacktestMultiRoute
  '/history': typeof HistoryRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/walk-forward': typeof WalkForwardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/backtest-decisions': typeof BacktestDecisionsRoute
  '/backtest-multi': typeof BacktestMultiRoute
  '/history': typeof HistoryRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/walk-forward': typeof WalkForwardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/backtest-decisions'
    | '/backtest-multi'
    | '/history'
    | '/operations'
    | '/settings'
    | '/walk-forward'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/backtest-decisions'
    | '/backtest-multi'
    | '/history'
    | '/operations'
    | '/settings'
    | '/walk-forward'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/backtest-decisions'
    | '/backtest-multi'
    | '/history'
    | '/operations'
    | '/settings'
    | '/walk-forward'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  BacktestRoute: typeof BacktestRoute
  BacktestDecisionsRoute: typeof BacktestDecisionsRoute
  BacktestMultiRoute: typeof BacktestMultiRoute
  HistoryRoute: typeof HistoryRoute
  OperationsRoute: typeof OperationsRoute
  SettingsRoute: typeof SettingsRoute
  WalkForwardRoute: typeof WalkForwardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walk-forward': {
      id: '/walk-forward'
      path: '/walk-forward'
      fullPath: '/walk-forward'
      preLoaderRoute: typeof WalkForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest-multi': {
      id: '/backtest-multi'
      path: '/backtest-multi'
      fullPath: '/backtest-multi'
      preLoaderRoute: typeof BacktestMultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest-decisions': {
      id: '/backtest-decisions'
      path: '/backtest-decisions'
      fullPath: '/backtest-decisions'
      preLoaderRoute: typeof BacktestDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  BacktestRoute: BacktestRoute,
  BacktestDecisionsRoute: BacktestDecisionsRoute,
  BacktestMultiRoute: BacktestMultiRoute,
  HistoryRoute: HistoryRoute,
  OperationsRoute: OperationsRoute,
  SettingsRoute: SettingsRoute,
  WalkForwardRoute: WalkForwardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
